"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Express = require("express");
const path = require("path");
const logger = require("morgan");
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const app = Express();
const webApp = Express();
const docsApp = Express();
webApp.use(Express.static(path.join(__dirname, '/public/webapp')));
docsApp.use(Express.static(path.join(__dirname, '/public/docs')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use('/', Express.static(path.join(__dirname, '/public/startpage')));
app.use('/app', webApp);
app.use('/docs', docsApp);
//app.use(Express.static(path.join(__dirname, '/public' )));
app.use(Express.static(path.join(__dirname, '/public/webapp')));
app.listen(3000, function () {
    console.log('meetznow.io is listening on port 3000!');
});
//app.use('/', require("./routes/index"));
